[workspace]

resolver = "2"

members = [
    "common",
    "rust_advent_2023",
    "day01",
    "day08",
    "day09",
]

[workspace.lints.rust]
non_snake_case = "allow"

[workspace.dependencies]
clap = { version = "4.4.11", features = ["derive"] }
nom = "7.1.3"
num = "0.4.1"
