[package]
name = "day09"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {workspace = true}
common = {path = "../common"}
itertools = {workspace = true}
nom = {workspace = true}
num = {workspace = true}

[lints]
workspace = true
